project_id = "snkdharivpouflpttllo"

[functions.geocode]
verify_jwt = false

[functions.ose-wells]
verify_jwt = false

[functions.plss-lookup]
verify_jwt = false

[functions.autocomplete]
verify_jwt = false

[functions.property-lookup]
verify_jwt = false
